POST http://localhost:5000/patients 
Content-Type: application/json 

{
    "name": "Evoing",
    "address": "123 Hills, Dubai, Emirates",
    "email": "new-email_kafka@example.com",
    "dateOfBirth": "2000-06-30",
    "registrationDate": "2025-12-02"
}

# content header is the type of the original resouce, so sending this as a json file, informs the client of the returned data