package com.pm.billing_service.grpc;

import org.slf4j.LoggerFactory;
import billing.BillingRequest;
import billing.BillingResponse;
import billing.BillingServiceGrpc.BillingServiceImplBase; // comes from the "billing" package generated by maven compile
import io.grpc.stub.StreamObserver;
import net.devh.boot.grpc.server.service.GrpcService;

// tell string this is a grpc service
@GrpcService
public class BillingGrpcService extends BillingServiceImplBase {

    private static final org.slf4j.Logger log = 
    LoggerFactory.getLogger(BillingGrpcService.class);
    // stream observer allows back and forth communication between client and server as opposed to rest api that require you to repeatedly make api calls to communicate
    @Override // override method in implBase class
    public void createBillingAccount(BillingRequest billingRequest, 
        StreamObserver<billing.BillingResponse> responseObserver
    ) {
        // check if server accepts requests
        log.info("\ncreateBillingAccount request received {}", billingRequest.toString());

        // implement business logic - save to db, perform calculation etc
        // builder pattern in Java, an alternative to creating an object and passing all values to the constructor
        // set each field explicitly and call the build() function to construct the BillingResponse object
        BillingResponse response = BillingResponse.newBuilder() // dummy data for testing purposes
        .setAccountId("12345")
        .setStatus("Active")
        .build();

        responseObserver.onNext(response); // send response from grpc service to client (patient service)
        responseObserver.onCompleted(); // response is completed, ready to end cycle of this reponse

        // multiple responses can be sent, via multiple lines of onNext() calls
    }

}
