# lets us define values for the configuration during production and testing
spring.application.name=patient-service
spring.h2.console.enabled=true
# provides an endpoint to the database to view the contents of the table
spring.h2.console.path=/h2-console
# jdbc is the connectivity protocol, h2 is the db type, mem is the in memory db and testdb is the name of the db
spring.datasource.url=jdbc:h2:mem:testdb
# using the h2 driver in coordination with the jdbc
spring.datasource.driver-class-name=org.h2.Driver
# credentials
spring.datasource.username=admin
spring.datasource.password=password123
# specifying the dialect of the db we are connecting to
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# update db if any changes to entity is detected
spring.jpa.hibernate.ddl-auto=update
# perform checks to ensure db and patient entity are in sync
spring.sql.init.mode=always
# all microservices will be on this range.
server.port=5000