# log a user in
POST http://localhost:4005/login
Content-Type: application/json

{
    "email": "test@email.com",
    "password": "password123"
}

# send login in request via frontend

# POST http://localhost:5004/auth/login
# Content-Type: application/json

# {
#     "email": "test@email.com",
#     "password": "password123"
# }