name: Java build with Maven

on: 
  push:
    branches: ["main"]
    # paths is just the condition - start the action if a push commit is made on the main branch and affects these files
    paths:
      - "analytics-service/**"
      - "api-gateway/**"
      - "auth-service/**"
      - "billing-service/**"
      - "patient-service/**"
      - "infrastructure/**"

jobs:
# name of the job
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up jdk-21
        uses: actions/setup-java@v4
        with: 
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build the application
        run: |
          mvn install -f analytics-service/pom.xml
          mvn install -f api-gateway/pom.xml
          mvn install -f auth-service/pom.xml
          mvn install -f billing-service/pom.xml
          mvn install -f patient-service/pom.xml

      - name: Build dependency graph - patient-service
        uses: advanced-security/maven-dependency-submission-action@v4
        with:
          directory: patient-service

      - name: Build dependency graph - billing-service
        uses: advanced-security/maven-dependency-submission-action@v4
        with:
          directory: billing-service

      - name: Build dependency graph - auth-service
        uses: advanced-security/maven-dependency-submission-action@v4
        with:
          directory: auth-service

      - name: Build dependency graph - api-gateway
        uses: advanced-security/maven-dependency-submission-action@v4
        with:
          directory: api-gateway

      - name: Build dependency graph - analytics-service
        uses: advanced-security/maven-dependency-submission-action@v4
        with:
          directory: analytics-service

      - name: Build dependency graph - infrastructure
        uses: advanced-security/maven-dependency-submission-action@v4
        with:
          directory: infrastructure



